name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/rtx-action@v1
      - run: |-
          rtx install
          shellcheck bin/*

  rtx_test:
    name: rtx test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/rtx-action@v1
      - run: |-
          rtx plugin add "file://$PWD"
          rtx use dt@latest
          rtx x -- dt --version

  asdf_test:
    name: asdf test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v2
      - run: |-
          asdf plugin add dt .
          asdf install dt latest
          asdf local dt latest
          asdf exec dt --version
